# Generated by Django 4.1.7 on 2023-03-31 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(default='localhost:8000/', max_length=100)),
                ('displayName', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('profileImage', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='users.profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
