# Generated by Django 2.2.18 on 2023-04-02 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_auto_20230402_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('contentType', models.TextField(default='type placeholder')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100, null=True)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('contentType', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(default=0, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_photo')),
                ('visibility', models.CharField(blank=True, max_length=150, null=True)),
                ('unlisted', models.BooleanField(default=False, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.User')),
                ('comments', models.ManyToManyField(blank=True, to='stream.Comment')),
            ],
        ),
    ]
