# Generated by Django 2.2.18 on 2023-04-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20230402_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='posts',
            name='comment_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='view_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
