# Generated by Django 2.2.18 on 2023-04-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230402_0958'),
        ('stream', '0005_remove_comment_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='LikeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.Posts')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
