# Generated by Django 2.2.18 on 2023-04-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_auto_20230402_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='friends_public',
            field=models.BooleanField(default=False),
        ),
    ]
