# Generated by Django 4.2 on 2023-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_auto_20230402_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='uuid',
            field=models.CharField(default='7951fd30-77e3-42ce-8ce8-122ee131787f', max_length=255, unique=True),
        ),
    ]
