# Generated by Django 2.2.18 on 2023-04-02 09:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('displayName', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.BooleanField(default=1, verbose_name='phone')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('host', models.CharField(default='localhost:8000/', max_length=100)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('profileImage', models.ImageField(default='profile_pics/happy-face.png', upload_to='profile_pics')),
                ('is_active', models.BooleanField(default=0, verbose_name='can login')),
                ('is_delete', models.BooleanField(default=0, verbose_name='is delete')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=256)),
                ('create_user_name', models.CharField(max_length=256)),
                ('follow_to', models.CharField(max_length=256)),
                ('follow_time', models.DateTimeField(auto_now_add=True)),
                ('is_followed', models.BooleanField(default=0)),
                ('hosts', models.TextField(default='')),
                ('follow_to_hosts', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.CharField(max_length=256)),
                ('create_user_name', models.CharField(max_length=256)),
                ('friend_to', models.CharField(max_length=256)),
                ('friend_to_username', models.CharField(max_length=256)),
                ('is_agreed', models.BooleanField(default=0)),
                ('friend_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('hosts', models.TextField(default='')),
                ('friend_to_hosts', models.TextField(default='')),
            ],
        ),
    ]
