# Generated by Django 2.2.18 on 2023-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230402_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='follow_to_username',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
