# Generated by Django 2.2.18 on 2023-04-02 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userinbux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinbux',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
