# Generated by Django 2.2.18 on 2023-04-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230402_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinbux',
            name='create_username',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinbux',
            name='operator_username',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
