# Generated by Django 2.2.18 on 2023-04-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230402_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinbux',
            name='source_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
